name: cellxgene-env
channels:
  - conda-forge
dependencies:
  - python=3.10  # Compatible with all packages listed
  - pip
  - pip:
      - anndata==0.11.4
      - cellxgene-census==1.17.0
      - scanpy==1.11.2
